In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urlencode
import csv

We will start by creating an object (list of URLs) containing the website address for the pages we want to scrape.

 We will scrape the first five pages of the search results. 
 
 When you are on the website ........and search and get results for the reviews ....... and then click the Next page button........ the web page address changes slightly

In [2]:
# Define a list of URL's that will be scraped.
list_of_urls = ['https://www.amazon.com/Apple-Watch-Cellular-Midnight-Aluminum/product-reviews/B09PB1PTH8/ref=cm_cr_othr_d_show_all_btm?ie=UTF8&reviewerType=all_reviews',
'https://www.amazon.com/Apple-Watch-Cellular-Midnight-Aluminum/product-reviews/B09PB1PTH8/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2',
'https://www.amazon.com/Apple-Watch-Cellular-Midnight-Aluminum/product-reviews/B09PB1PTH8/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3',
'https://www.amazon.com/Apple-Watch-Cellular-Midnight-Aluminum/product-reviews/B09PB1PTH8/ref=cm_cr_getr_d_paging_btm_next_4?ie=UTF8&reviewerType=all_reviews&pageNumber=4',
'https://www.amazon.com/Apple-Watch-Cellular-Midnight-Aluminum/product-reviews/B09PB1PTH8/ref=cm_cr_getr_d_paging_btm_next_5?ie=UTF8&reviewerType=all_reviews&pageNumber=5']

 We will be using the ScraperAPI proxy manager. 

 Reason for using ScraperAPI    -    When you  run the code to access and extract data elements from the web pages......... you might be  blocked numerous times by Amazon’s anti-bot detectors ............. and might be  denied access to their web pages. 
 
 To resolve this issue we will be using ScraperAPI

ScraperAPI handles proxies, browsers, and CAPTCHAs, so you can get the HTML from any web page with a simple API call without being blocked. 

ScraperAPI offers a free trial period to test and verify its services. 

There are also several other proxy managers on the market that you can use. 

 To use the ScraperAPI proxy manager service....... you will need to create an account at this link and you will receive a unique API key.

In [3]:
# Retrieve each of the url's HTML data and convert the data into a beautiful soup object.  
# Find, extract and store reviewer names and review text into a list.

names = []
reviews = []
data_string = ""

for url in list_of_urls: 
    params = {'api_key': "7daf3c005f45ff015d13e4cd97de8b1e" , 'url': url}
    response = requests.get('http://api.scraperapi.com/',   params=urlencode(params))
    soup = BeautifulSoup(response.text, 'html.parser')

    for item in soup.find_all("span", class_="a-profile-name"):
      data_string = data_string + item.get_text()
      names.append(data_string)
      data_string = ""  
    
    for item in soup.find_all("span", {"data-hook": "review-body"}):
      data_string = data_string + item.get_text()
      reviews.append(data_string)
      data_string = ""

In [4]:
# Create the dictionary.
reviews_dict = {'Reviewer Name': names, 'Reviews': reviews}


# Print the lengths of each list.  
print(len(names), len(reviews))

60 50

In [5]:
# Create a new dataframe.
df = pd.DataFrame.from_dict(reviews_dict, orient='index')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
Reviewer Name,Violet Sunshine,Disciple,Violet Sunshine,Joanne Robertson,Florencia,David,Disciple,Travis,Austin Richardson,Amazon Customer,...,Dustin Spray,Ella M. Ryder,thevin,Quite Contrary,Brittney,jeanette s.,Mary Barton,Julián rojas,Rebecca Liller,Riley G
Reviews,\nApple has a reputation for having the best q...,\nI actually bought a refurbished watch in “ex...,\nGood product and very nice size\n,\nI can’t tell this was a refurb. The packagin...,\nBattery only lasts 1 day! Periodically it ch...,\nI wish I would’ve got the 45\n,"\nBought this for myself months ago, watch cam...",\nEverything looks and feels new for a resale ...,\nOrdered this refurbished watch and the watch...,\nGreat product. Syncs well with my iPhone. Ba...,...,None,None,None,None,None,None,None,None,None,None

In [6]:
# Delete all the columns that have missing values.
df.dropna(axis=1, inplace=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
Reviewer Name,Violet Sunshine,Disciple,Violet Sunshine,Joanne Robertson,Florencia,David,Disciple,Travis,Austin Richardson,Amazon Customer,...,MuffinMix,John,Andrew C Barker,Norman C. Straker,Machele Lugo,travis schwarz,Stephanie Paulette,S. J. Twigg,Violet Sunshine,Disciple
Reviews,\nApple has a reputation for having the best q...,\nI actually bought a refurbished watch in “ex...,\nGood product and very nice size\n,\nI can’t tell this was a refurb. The packagin...,\nBattery only lasts 1 day! Periodically it ch...,\nI wish I would’ve got the 45\n,"\nBought this for myself months ago, watch cam...",\nEverything looks and feels new for a resale ...,\nOrdered this refurbished watch and the watch...,\nGreat product. Syncs well with my iPhone. Ba...,...,\nCouldn't even use bc it was connected to som...,"\nToo hard to figure it out, especially for se...",\nI got the “green snake of death” or “red sna...,\nDoesn’t turn on and the wrong charge cube wa...,\nI got this watch today Having a hard time pa...,\nThis is not a brand new watch\n,\nThe watch only comes with half a charger. Yo...,\nBufno\n,\nSo far I love or. No issues with delivery or...,\nReceived the watch in the mail and it wouldn...

In [7]:
# Transpose the dataframe.
prod_reviews = df.T
print(prod_reviews.head(10))

       Reviewer Name                                            Reviews
0    Violet Sunshine  \nApple has a reputation for having the best q...
1           Disciple  \nI actually bought a refurbished watch in “ex...
2    Violet Sunshine                \nGood product and very nice size\n
3   Joanne Robertson  \nI can’t tell this was a refurb. The packagin...
4          Florencia  \nBattery only lasts 1 day! Periodically it ch...
5              David                   \nI wish I would’ve got the 45\n
6           Disciple  \nBought this for myself months ago, watch cam...
7             Travis  \nEverything looks and feels new for a resale ...
8  Austin Richardson  \nOrdered this refurbished watch and the watch...
9    Amazon Customer  \nGreat product. Syncs well with my iPhone. Ba...

In [8]:
# Remove special characters from review text.
prod_reviews['Reviews'] = prod_reviews['Reviews'].str.replace('\n','')
prod_reviews.head(5)

      Reviewer Name                                            Reviews
0   Violet Sunshine  Apple has a reputation for having the best qua...
1          Disciple  I actually bought a refurbished watch in “exce...
2   Violet Sunshine                    Good product and very nice size
3  Joanne Robertson  I can’t tell this was a refurb. The packaging ...
4         Florencia  Battery only lasts 1 day! Periodically it chan...

In [13]:
# Convert dataframe to CSV file.
prod_reviews.to_csv('reviews.csv', index=False, header=True)

In [14]:
new_df = pd.read_csv('reviews.csv')
 
print(new_df)

             Reviewer Name                                            Reviews
0          Violet Sunshine  Apple has a reputation for having the best qua...
1                 Disciple  I actually bought a refurbished watch in “exce...
2          Violet Sunshine                    Good product and very nice size
3         Joanne Robertson  I can’t tell this was a refurb. The packaging ...
4                Florencia  Battery only lasts 1 day! Periodically it chan...
5                    David                       I wish I would’ve got the 45
6                 Disciple  Bought this for myself months ago, watch came ...
7                   Travis   Everything looks and feels new for a resale item
8        Austin Richardson  Ordered this refurbished watch and the watch i...
9          Amazon Customer  Great product. Syncs well with my iPhone. Batt...
10             Amanda Boyd  Battery dies fast, charger didn’t work, watch ...
11          Anthony Taylor  I can’t even charge my watch right off the bat...
12         Violet Sunshine                                        Works great
13                Disciple                                        I love it .
14                      Cw                      Gift to my niece who is an RN
15           Sheila Larson                                                NaN
16                  DUSTIN  It’s a great watch. Although trying to hook th...
17              Denisnunez  didn't realized it was renewed.  Charging cord...
18          Anita O Morris                                       looks great.
19                Jas Rose  My watch arrived quickly and the set up was se...
20          Lorraine Spain  Battery only last a day compared to my Garmin ...
21       Richard A. Callis  Was supposed to include a sim removal tool and...
22         Toribio Polanco                                                NaN
23                britt.b.                         It was just what I needed.
24         Violet Sunshine  This watch is wonderful! It has done everythin...
25                Disciple  There was no SIM card tool and did not include...
26                   Brian            Came in perfect condition in great time
27         Amazon Customer             Value for money, seller was courteous.
28  VILMAR JUNIOR DA SILVA  It seem to be working fine didn’t get the righ...
29         Beckie Townsend  Came in a timely manner and is exactly what th...
30                  Margie                                     disliked band.
31           ERIC P FELTON  Fake belt, Fake charging cable, and god knows ...
32            Serena Perez  Watch will not charge.  They should at least s...
33               T. Fasasi    watch does not turn on return is very difficult
34                    Nate  So we got the watch and everything works fine,...
35              Jamie Love  Thought I ordered a new watch, not a refurbish...
36         Violet Sunshine  Do not use this seller. The battery lasted 2 h...
37                Disciple  I purchased a series 7 Apple Watch from this c...
38        Pete the shopper  Bought this and charged it all day. It died wi...
39              Shobhit M.  The Watch looks good and works well, but the b...
40               MuffinMix  Couldn't even use bc it was connected to someo...
41                    John  Too hard to figure it out, especially for seni...
42         Andrew C Barker  I got the “green snake of death” or “red snake...
43       Norman C. Straker  Doesn’t turn on and the wrong charge cube was ...
44            Machele Lugo  I got this watch today Having a hard time pair...
45          travis schwarz                      This is not a brand new watch
46      Stephanie Paulette  The watch only comes with half a charger. You ...
47             S. J. Twigg                                              Bufno
48         Violet Sunshine  So far I love or. No issues with delivery or p...
49                Disciple  Received the watch in the mail and it wouldn’t...